---
# - name: Check if Apache is installed
#   ansible.builtin.shell: dpkg -l | grep apache2
#   register: apache_check
#   ignore_errors: yes
#
# - name: Ensure Apache is stopped and disabled
#   ansible.builtin.service:
#     name: apache2
#     state: stopped
#     enabled: no
#   ignore_errors: yes  # In case Apache isn't installed
#
# - name: Remove Apache if installed
#   ansible.builtin.apt:
#     name: apache2
#     state: absent
#     purge: yes
#   ignore_errors: yes
#
# - name: Debug Apache status
#   ansible.builtin.debug:
#     msg: "Apache was installed and has now been removed."
#   when: apache_check.rc == 0
#
# - name: Purge Apache completely
#   ansible.builtin.apt:
#     name: apache2*
#     state: absent
#     purge: yes
#     autoremove: yes
#     update_cache: yes

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root
  notify: Restart HAProxy

- meta: flush_handlers

- name: Wait for HAProxy to be available on port 80
  ansible.builtin.wait_for:
    port: 80
    host: 127.0.0.1
    delay: 2
    timeout: 10
    state: started


