---
- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: DEBUG - Show NFS mount variables
  debug:
    msg:
      - "nfs_server: {{ nfs_server | default('undefined') }}"
      - "nfs_export_path: {{ nfs_export_path | default('undefined') }}"
      - "nfs_mount_path: {{ nfs_mount_path | default('undefined') }}"

- name: Create mount directory
  file:
    path: "{{ nfs_mount_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0770'

- name: Wait for NFS server to be ready
  wait_for:
    host: "{{ nfs_server }}"
    port: 2049
    delay: 5
    timeout: 60

- name: Mount NFS share and make it persistent
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_export_path }}"
    path: "{{ nfs_mount_path }}"
    fstype: nfs
    opts: rw
    state: mounted
